In [28]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv("Data/Data_train.csv")

In [30]:
df.head()

       Airline Date_of_Journey    Source Dep_Time Destination  Class  Price
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi      0   3897
1    Air India       1/05/2019   Kolkata    05:50    Banglore      0   7662
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin      0  13882
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore      0   6218
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi      0  13302

In [31]:
df.tail()

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Class,Price
10678,Air Asia,9/04/2019,Kolkata,19:55,Banglore,0,4107
10679,Air India,27/04/2019,Kolkata,20:45,Banglore,0,4145
10680,Jet Airways,27/04/2019,Banglore,08:20,Delhi,0,7229
10681,Vistara,01/03/2019,Banglore,11:30,New Delhi,0,12648
10682,Air India,9/05/2019,Delhi,10:55,Cochin,0,11753

In [32]:
#Check null
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Dep_Time           0
Destination        0
Class              0
Price              0
dtype: int64

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Dep_Time         10683 non-null  object
 4   Destination      10683 non-null  object
 5   Class            10683 non-null  int64
 6   Price            10683 non-null  int64
dtypes: int64(2), object(5)
memory usage: 584.4+ KB

In [34]:
#check-unique
df.nunique()

Airline              12
Date_of_Journey      44
Source                5
Dep_Time            222
Destination           6
Class                 1
Price              1870
dtype: int64

In [35]:
df.shape

(10683, 7)

In [36]:
df[df.duplicated()]

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Class,Price
183,Jet Airways,6/05/2019,Kolkata,20:00,Banglore,0,9663
236,Jet Airways,6/03/2019,Delhi,18:15,Cochin,0,17024
287,Jet Airways,24/06/2019,Delhi,09:00,Cochin,0,10262
310,Jet Airways,21/05/2019,Kolkata,20:00,Banglore,0,10844
400,Jet Airways,12/03/2019,Banglore,18:55,New Delhi,0,11087
...,...,...,...,...,...,...,...
10667,Jet Airways,12/03/2019,Banglore,22:55,New Delhi,0,11087
10670,Air India,12/05/2019,Kolkata,05:50,Banglore,0,11411
10672,Jet Airways,27/06/2019,Delhi,23:05,Cochin,0,11150
10673,Jet Airways,27/05/2019,Delhi,13:25,Cochin,0,16704
10674,Jet Airways,12/03/2019,Banglore,20:35,New Delhi,0,11087

In [37]:
#check duplicate
df.duplicated().sum()

2001

In [38]:
duplicates_3_rows = (
    df.groupby(df.columns.tolist(), dropna=False)
      .size()
      .reset_index(name="count")
)

duplicates_3_rows = duplicates_3_rows[
    duplicates_3_rows["count"] == 3
]

duplicates_3_rows

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Class,Price,count
342,Air India,03/03/2019,Banglore,08:15,New Delhi,0,6781,3
348,Air India,03/03/2019,Banglore,10:30,New Delhi,0,11003,3
382,Air India,09/03/2019,Banglore,22:00,New Delhi,0,8425,3
413,Air India,1/04/2019,Kolkata,12:00,Banglore,0,9258,3
418,Air India,1/04/2019,Kolkata,16:45,Banglore,0,9920,3
...,...,...,...,...,...,...,...,...
8468,Vistara,21/05/2019,Kolkata,20:20,Banglore,0,9345,3
8521,Vistara,24/05/2019,Kolkata,17:00,Banglore,0,9870,3
8525,Vistara,24/05/2019,Kolkata,20:20,Banglore,0,9345,3
8590,Vistara,6/03/2019,Mumbai,15:40,Hyderabad,0,12395,3
8592,Vistara,6/03/2019,Mumbai,21:55,Hyderabad,0,12395,3

In [39]:
df_duplicate = df[df.duplicated(keep=False)]

In [40]:
df_duplicate

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Class,Price
2,Jet Airways,9/06/2019,Delhi,09:25,Cochin,0,13882
6,Jet Airways,12/03/2019,Banglore,18:55,New Delhi,0,11087
7,Jet Airways,01/03/2019,Banglore,08:00,New Delhi,0,22270
13,Jet Airways,9/05/2019,Kolkata,21:10,Banglore,0,9663
17,Jet Airways,12/06/2019,Delhi,14:00,Cochin,0,10262
...,...,...,...,...,...,...,...
10667,Jet Airways,12/03/2019,Banglore,22:55,New Delhi,0,11087
10670,Air India,12/05/2019,Kolkata,05:50,Banglore,0,11411
10672,Jet Airways,27/06/2019,Delhi,23:05,Cochin,0,11150
10673,Jet Airways,27/05/2019,Delhi,13:25,Cochin,0,16704
10674,Jet Airways,12/03/2019,Banglore,20:35,New Delhi,0,11087

In [41]:
#sắp xếp các dòng nằm cạnh nhau
duplicates = df[
    df.duplicated(keep=False)
].sort_values(by=df.columns.tolist())

duplicates

       Airline Date_of_Journey   Source Dep_Time Destination  Class  Price
2186  Air Asia       1/06/2019    Delhi    16:45      Cochin      0  11410
3255  Air Asia       1/06/2019    Delhi    16:45      Cochin      0  11410
4064  Air Asia      12/05/2019  Kolkata    07:35    Banglore      0   5320
7924  Air Asia      12/05/2019  Kolkata    07:35    Banglore      0   5320
6373  Air Asia      12/06/2019    Delhi    07:55      Cochin      0   6152
...        ...             ...      ...      ...         ...    ...    ...
5994   Vistara       9/06/2019  Kolkata    07:10    Banglore      0   9397
216    Vistara       9/06/2019  Kolkata    07:10    Banglore      0   9555
3617   Vistara       9/06/2019  Kolkata    07:10    Banglore      0   9555
2873   Vistara       9/06/2019  Kolkata    20:20    Banglore      0   8085
7625   Vistara       9/06/2019  Kolkata    20:20    Banglore      0   8085

[3192 rows x 7 columns]

In [42]:
df = df.drop_duplicates()

In [43]:
df.shape

(8682, 7)

In [44]:
duplicates = df[
    df.duplicated(keep=False)
].sort_values(by=df.columns.tolist())

duplicates

Empty DataFrame
Columns: [Airline, Date_of_Journey, Source, Dep_Time, Destination, Class, Price]
Index: []

In [45]:
df.head()

       Airline Date_of_Journey    Source Dep_Time Destination  Class  Price
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi      0   3897
1    Air India       1/05/2019   Kolkata    05:50    Banglore      0   7662
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin      0  13882
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore      0   6218
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi      0  13302

In [46]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Dep_Time', 'Destination',
       'Class', 'Price'],
      dtype='object')

In [47]:
df.describe()

        Class         Price
count  8682.0   8682.000000
mean      0.0   8434.731283
std       0.0   4605.337734
min       0.0   1759.000000
25%       0.0   4823.000000
50%       0.0   7229.000000
75%       0.0  11410.000000
max       0.0  79512.000000

In [48]:
df['Airline'].value_counts()

Airline
Jet Airways                          2289
IndiGo                               1989
Air India                            1563
Multiple carriers                    1100
SpiceJet                              815
Vistara                               422
Air Asia                              288
GoAir                                 194
Multiple carriers Premium economy      12
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [49]:
df['Source'].value_counts()

Source
Delhi       3685
Kolkata     2014
Banglore    1918
Mumbai       684
Chennai      381
Name: count, dtype: int64

In [50]:
df['Destination'].value_counts()

Destination
Cochin       3685
Banglore     2014
Delhi        1265
Hyderabad     684
New Delhi     653
Kolkata       381
Name: count, dtype: int64

In [51]:
df['Class'].value_counts()

Class
0    8682
Name: count, dtype: int64

In [52]:
df.head()

       Airline Date_of_Journey    Source Dep_Time Destination  Class  Price
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi      0   3897
1    Air India       1/05/2019   Kolkata    05:50    Banglore      0   7662
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin      0  13882
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore      0   6218
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi      0  13302

In [54]:
df = df.drop(columns='Class',axis=1)

In [55]:
df.head()

       Airline Date_of_Journey    Source Dep_Time Destination  Price
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi   3897
1    Air India       1/05/2019   Kolkata    05:50    Banglore   7662
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin  13882
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore   6218
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi  13302

In [56]:
categorical_columns = df.columns[df.dtypes == 'object']
numerical_columns = df.columns[df.dtypes !='object']

In [58]:
df[categorical_columns].head()

       Airline Date_of_Journey    Source Dep_Time Destination
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi
1    Air India       1/05/2019   Kolkata    05:50    Banglore
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi

In [ ]:
#Encoding for categorical columns
#It is a oridinal encoding