In [55]:
import pandas as pd
import numpy as np

In [56]:
data = pd.read_csv("Data/Data_train.csv")

In [57]:
data.head()

       Airline Date_of_Journey    Source Dep_Time Destination  Class  Price
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi      0   3897
1    Air India       1/05/2019   Kolkata    05:50    Banglore      0   7662
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin      0  13882
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore      0   6218
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi      0  13302

In [58]:
data.drop_duplicates()

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Class,Price
0,IndiGo,24/03/2019,Banglore,22:20,New Delhi,0,3897
1,Air India,1/05/2019,Kolkata,05:50,Banglore,0,7662
2,Jet Airways,9/06/2019,Delhi,09:25,Cochin,0,13882
3,IndiGo,12/05/2019,Kolkata,18:05,Banglore,0,6218
4,IndiGo,01/03/2019,Banglore,16:50,New Delhi,0,13302
...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,19:55,Banglore,0,4107
10679,Air India,27/04/2019,Kolkata,20:45,Banglore,0,4145
10680,Jet Airways,27/04/2019,Banglore,08:20,Delhi,0,7229
10681,Vistara,01/03/2019,Banglore,11:30,New Delhi,0,12648
10682,Air India,9/05/2019,Delhi,10:55,Cochin,0,11753

In [59]:
X = data.drop(labels=['Price'],axis=1)

In [60]:
y  = data[["Price"]]

In [61]:
X = X.drop(labels=['Class'],axis=1)

In [62]:
X.head()

       Airline Date_of_Journey    Source Dep_Time Destination
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi
1    Air India       1/05/2019   Kolkata    05:50    Banglore
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi

In [63]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Dep_Time         10683 non-null  object
 4   Destination      10683 non-null  object
dtypes: object(5)
memory usage: 417.4+ KB

In [64]:
X.select_dtypes(include="object")

           Airline Date_of_Journey    Source Dep_Time Destination
0           IndiGo      24/03/2019  Banglore    22:20   New Delhi
1        Air India       1/05/2019   Kolkata    05:50    Banglore
2      Jet Airways       9/06/2019     Delhi    09:25      Cochin
3           IndiGo      12/05/2019   Kolkata    18:05    Banglore
4           IndiGo      01/03/2019  Banglore    16:50   New Delhi
...            ...             ...       ...      ...         ...
10678     Air Asia       9/04/2019   Kolkata    19:55    Banglore
10679    Air India      27/04/2019   Kolkata    20:45    Banglore
10680  Jet Airways      27/04/2019  Banglore    08:20       Delhi
10681      Vistara      01/03/2019  Banglore    11:30   New Delhi
10682    Air India       9/05/2019     Delhi    10:55      Cochin

[10683 rows x 5 columns]

In [65]:
X['Destination'].value_counts()

Destination
Cochin       4537
Banglore     2871
Delhi        1265
New Delhi     932
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [66]:
#Define the custom ranking for each ordinal variable
airline_categories = ["Jet Airways", "IndiGo", "Air India","Multiple carriers","SpiceJet","Vistara","Air Asia","GoAir","Multiple carriers Premium economy","Jet Airways Business","Vistara Premium economy","Trujet"]
source_categories = ["Delhi","Kolkata","Banglore","Mumbai","Chennai"]
destination_categories = ["Cochin","Banglore","Delhi","New Delhi","Hyderabad","Kolkata"]

In [67]:
#Date_of_journey --> Day, Month
X["Date_of_Journey"] = pd.to_datetime(
    X["Date_of_Journey"],
    format = "%d/%m/%Y"
)
X["Journey_Day"] = X["Date_of_Journey"].dt.day
X["Journey_Month"] = X["Date_of_Journey"].dt.month

#Dep_time --> Hour, Minute
# Dep_Time → Hour, Minute
X["Dep_Time"] = pd.to_datetime(
    X["Dep_Time"],
    format="%H:%M"
)

X["Dep_Hour"] = X["Dep_Time"].dt.hour
X["Dep_Minute"] = X["Dep_Time"].dt.minute

In [68]:
X.head()

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute
0,IndiGo,2019-03-24,Banglore,1900-01-01 22:20:00,New Delhi,24,3,22,20
1,Air India,2019-05-01,Kolkata,1900-01-01 05:50:00,Banglore,1,5,5,50
2,Jet Airways,2019-06-09,Delhi,1900-01-01 09:25:00,Cochin,9,6,9,25
3,IndiGo,2019-05-12,Kolkata,1900-01-01 18:05:00,Banglore,12,5,18,5
4,IndiGo,2019-03-01,Banglore,1900-01-01 16:50:00,New Delhi,1,3,16,50

In [69]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  datetime64[ns]
 2   Source           10683 non-null  object
 3   Dep_Time         10683 non-null  datetime64[ns]
 4   Destination      10683 non-null  object
 5   Journey_Day      10683 non-null  int32
 6   Journey_Month    10683 non-null  int32
 7   Dep_Hour         10683 non-null  int32
 8   Dep_Minute       10683 non-null  int32
dtypes: datetime64[ns](2), int32(4), object(3)
memory usage: 584.4+ KB

In [70]:
X = X.drop(["Date_of_Journey","Dep_Time"],axis=1)

In [71]:
X.head()

,Airline,Source,Destination,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,24,3,22,20
1,Air India,Kolkata,Banglore,1,5,5,50
2,Jet Airways,Delhi,Cochin,9,6,9,25
3,IndiGo,Kolkata,Banglore,12,5,18,5
4,IndiGo,Banglore,New Delhi,1,3,16,50

In [72]:
categorical_cols = X.select_dtypes(include="object").columns

In [73]:
numerical_cols = X.select_dtypes(exclude="object").columns

In [74]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [75]:
categorical_cols

Index(['Airline', 'Source', 'Destination'], dtype='object')

In [76]:
numerical_cols

Index(['Journey_Day', 'Journey_Month', 'Dep_Hour', 'Dep_Minute'], dtype='object')

In [77]:
number_pipeline = Pipeline(
    steps = [
        ('imputer',SimpleImputer()),
        ('scaler',StandardScaler())
    ]
)

In [78]:
cat_pipeline = Pipeline(
    steps =[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[airline_categories,source_categories,destination_categories]))
    ]
)

In [79]:
preprocessor = ColumnTransformer(
    [
        ('num_pipeline',number_pipeline, numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [80]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [81]:
preprocessor.fit_transform(X_train)

array([[-0.18720791, -1.46907017, -1.13039148, ...,  0.        ,
         3.        ,  4.        ],
       [-0.5411112 ,  0.25051258, -0.25952699, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.22840525, -0.60927879,  0.4371646 , ...,  4.        ,
         0.        ,  0.        ],
       ...,
       [ 0.16669538,  0.25051258, -0.0853541 , ...,  3.        ,
         0.        ,  0.        ],
       [-1.24891778, -1.46907017, -2.17542887, ...,  1.        ,
         2.        ,  3.        ],
       [-1.4848533 ,  1.11030396,  0.0888188 , ...,  0.        ,
         0.        ,  0.        ]])

In [82]:
preprocessor.transform(X_test)

array([[ 0.52059867,  0.25051258, -1.30456438, ...,  0.        ,
         1.        ,  1.        ],
       [-1.24891778,  1.11030396, -0.43369989, ...,  7.        ,
         0.        ,  0.        ],
       [-1.4848533 ,  0.25051258,  0.2629917 , ...,  0.        ,
         1.        ,  1.        ],
       ...,
       [ 0.87450196, -0.60927879, -0.95621859, ...,  6.        ,
         0.        ,  0.        ],
       [-0.5411112 , -0.60927879, -0.78204569, ...,  1.        ,
         2.        ,  2.        ],
       [-0.5411112 ,  1.11030396,  0.6113375 , ...,  0.        ,
         1.        ,  1.        ]])