In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Data/Data_train.csv")

In [3]:
data.head()

       Airline Date_of_Journey    Source Dep_Time Destination  Class  Price
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi      0   3897
1    Air India       1/05/2019   Kolkata    05:50    Banglore      0   7662
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin      0  13882
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore      0   6218
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi      0  13302

In [4]:
data.drop_duplicates()

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Class,Price
0,IndiGo,24/03/2019,Banglore,22:20,New Delhi,0,3897
1,Air India,1/05/2019,Kolkata,05:50,Banglore,0,7662
2,Jet Airways,9/06/2019,Delhi,09:25,Cochin,0,13882
3,IndiGo,12/05/2019,Kolkata,18:05,Banglore,0,6218
4,IndiGo,01/03/2019,Banglore,16:50,New Delhi,0,13302
...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,19:55,Banglore,0,4107
10679,Air India,27/04/2019,Kolkata,20:45,Banglore,0,4145
10680,Jet Airways,27/04/2019,Banglore,08:20,Delhi,0,7229
10681,Vistara,01/03/2019,Banglore,11:30,New Delhi,0,12648
10682,Air India,9/05/2019,Delhi,10:55,Cochin,0,11753

In [5]:
X = data.drop(labels=['Price'],axis=1)

In [6]:
y  = data[["Price"]]

In [7]:
X = X.drop(labels=['Class'],axis=1)

In [8]:
X.head()

       Airline Date_of_Journey    Source Dep_Time Destination
0       IndiGo      24/03/2019  Banglore    22:20   New Delhi
1    Air India       1/05/2019   Kolkata    05:50    Banglore
2  Jet Airways       9/06/2019     Delhi    09:25      Cochin
3       IndiGo      12/05/2019   Kolkata    18:05    Banglore
4       IndiGo      01/03/2019  Banglore    16:50   New Delhi

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Dep_Time         10683 non-null  object
 4   Destination      10683 non-null  object
dtypes: object(5)
memory usage: 417.4+ KB

In [10]:
X.select_dtypes(include="object")

           Airline Date_of_Journey    Source Dep_Time Destination
0           IndiGo      24/03/2019  Banglore    22:20   New Delhi
1        Air India       1/05/2019   Kolkata    05:50    Banglore
2      Jet Airways       9/06/2019     Delhi    09:25      Cochin
3           IndiGo      12/05/2019   Kolkata    18:05    Banglore
4           IndiGo      01/03/2019  Banglore    16:50   New Delhi
...            ...             ...       ...      ...         ...
10678     Air Asia       9/04/2019   Kolkata    19:55    Banglore
10679    Air India      27/04/2019   Kolkata    20:45    Banglore
10680  Jet Airways      27/04/2019  Banglore    08:20       Delhi
10681      Vistara      01/03/2019  Banglore    11:30   New Delhi
10682    Air India       9/05/2019     Delhi    10:55      Cochin

[10683 rows x 5 columns]

In [11]:
X['Destination'].value_counts()

Destination
Cochin       4537
Banglore     2871
Delhi        1265
New Delhi     932
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [12]:
#Define the custom ranking for each ordinal variable
airline_categories = ["Jet Airways", "IndiGo", "Air India","Multiple carriers","SpiceJet","Vistara","Air Asia","GoAir","Multiple carriers Premium economy","Jet Airways Business","Vistara Premium economy","Trujet"]
source_categories = ["Delhi","Kolkata","Banglore","Mumbai","Chennai"]
destination_categories = ["Cochin","Banglore","Delhi","New Delhi","Hyderabad","Kolkata"]

In [13]:
#Date_of_journey --> Day, Month
X["Date_of_Journey"] = pd.to_datetime(
    X["Date_of_Journey"],
    format = "%d/%m/%Y"
)
X["Journey_Day"] = X["Date_of_Journey"].dt.day
X["Journey_Month"] = X["Date_of_Journey"].dt.month

#Dep_time --> Hour, Minute
# Dep_Time → Hour, Minute
X["Dep_Time"] = pd.to_datetime(
    X["Dep_Time"],
    format="%H:%M"
)

X["Dep_Hour"] = X["Dep_Time"].dt.hour
X["Dep_Minute"] = X["Dep_Time"].dt.minute

In [14]:
X.head()

,Airline,Date_of_Journey,Source,Dep_Time,Destination,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute
0,IndiGo,2019-03-24,Banglore,1900-01-01 22:20:00,New Delhi,24,3,22,20
1,Air India,2019-05-01,Kolkata,1900-01-01 05:50:00,Banglore,1,5,5,50
2,Jet Airways,2019-06-09,Delhi,1900-01-01 09:25:00,Cochin,9,6,9,25
3,IndiGo,2019-05-12,Kolkata,1900-01-01 18:05:00,Banglore,12,5,18,5
4,IndiGo,2019-03-01,Banglore,1900-01-01 16:50:00,New Delhi,1,3,16,50

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  datetime64[ns]
 2   Source           10683 non-null  object
 3   Dep_Time         10683 non-null  datetime64[ns]
 4   Destination      10683 non-null  object
 5   Journey_Day      10683 non-null  int32
 6   Journey_Month    10683 non-null  int32
 7   Dep_Hour         10683 non-null  int32
 8   Dep_Minute       10683 non-null  int32
dtypes: datetime64[ns](2), int32(4), object(3)
memory usage: 584.4+ KB

In [16]:
X = X.drop(["Date_of_Journey","Dep_Time"],axis=1)

In [17]:
X.head()

,Airline,Source,Destination,Journey_Day,Journey_Month,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,24,3,22,20
1,Air India,Kolkata,Banglore,1,5,5,50
2,Jet Airways,Delhi,Cochin,9,6,9,25
3,IndiGo,Kolkata,Banglore,12,5,18,5
4,IndiGo,Banglore,New Delhi,1,3,16,50

In [18]:
categorical_cols = X.select_dtypes(include="object").columns

In [19]:
numerical_cols = X.select_dtypes(exclude="object").columns

In [20]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
from sklearn.preprocessing import OneHotEncoder #Onehot Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [21]:
categorical_cols

Index(['Airline', 'Source', 'Destination'], dtype='object')

In [22]:
numerical_cols

Index(['Journey_Day', 'Journey_Month', 'Dep_Hour', 'Dep_Minute'], dtype='object')

In [23]:
number_pipeline = Pipeline(
    steps = [
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())
    ]
)

In [24]:
cat_pipeline = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehotencoder', OneHotEncoder(
            handle_unknown='ignore',
            sparse_output=False
        ))
    ]
)

In [25]:
preprocessor = ColumnTransformer(
    [
        ('num_pipeline',number_pipeline, numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [26]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [27]:
preprocessor.fit_transform(X_train)[0]

array([-0.18720791, -1.46907017, -1.13039148,  0.29805099,  0.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ])

In [28]:
preprocessor.transform(X_test)

array([[ 0.52059867,  0.25051258, -1.30456438, ...,  0.        ,
         0.        ,  0.        ],
       [-1.24891778,  1.11030396, -0.43369989, ...,  0.        ,
         0.        ,  0.        ],
       [-1.4848533 ,  0.25051258,  0.2629917 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.87450196, -0.60927879, -0.95621859, ...,  0.        ,
         0.        ,  0.        ],
       [-0.5411112 , -0.60927879, -0.78204569, ...,  0.        ,
         0.        ,  0.        ],
       [-0.5411112 ,  1.11030396,  0.6113375 , ...,  0.        ,
         0.        ,  0.        ]])

In [29]:
x_train = preprocessor.fit_transform(X_train)
x_test = preprocessor.transform(X_test)
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)

In [30]:
#Build the regression / Regressor models

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingRegressor

#Create objects of Regression/ Regressor models with default hyper-parameter
modelmlg = LinearRegression()
modeldcr = DecisionTreeRegressor()
modelbag = BaggingRegressor()
modelrfr = RandomForestRegressor()
modelSVR = SVR()
modelXGR = xgb.XGBRegressor()
modelKNN = KNeighborsRegressor(n_neighbors=5)
modelETR = ExtraTreesRegressor()
modelRE=Ridge()
modelLO=linear_model.Lasso(alpha=0.1)

modelGBR = GradientBoostingRegressor(loss='squared_error', learning_rate=0.1, n_estimators=100, subsample=1.0,
                                     criterion='friedman_mse', min_samples_split=2, min_samples_leaf=1,
                                     min_weight_fraction_leaf=0.0, max_depth=3, min_impurity_decrease=0.0,
                                     init=None, random_state=None, max_features=None,
                                     alpha=0.9, verbose=0, max_leaf_nodes=None, warm_start=False,
                                     validation_fraction=0.1, n_iter_no_change=None, tol=0.0001, ccp_alpha=0.0)

In [31]:
# Evalution matrix for all the algorithms
MM = [modelmlg, modeldcr, modelrfr, modelKNN, modelETR, modelGBR, modelXGR, modelbag,modelRE,modelLO]

In [32]:
results =[]
for models in MM:
    
    #Fit the model with train data
    models.fit(x_train, y_train)
    
    #Predict the model with test data
    
    y_pred = models.predict(x_test)
    
    #Print the model name
    
    print("Model name: ",models)
    
    #Evaluation metrics for Regression analysis
    
    from sklearn import metrics #Error (càng thấp càng tốt), score (Càng cao càng tốt)
    print('Mean Absolute Error (MAE):', round(metrics.mean_absolute_error(y_test, y_pred),3))  
    print('Mean Squared Error (MSE):', round(metrics.mean_squared_error(y_test, y_pred),3))  
    print('Root Mean Squared Error (RMSE):', round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3))
    print('R2_score:', round(metrics.r2_score(y_test, y_pred),6))
    print('Root Mean Squared Log Error (RMSLE):', round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3))
    # Define the function to calculate the MAPE - Mean Absolute Percentage Error

    def MAPE (y_test, y_pred):
        y_test, y_pred = np.array(y_test), np.array(y_pred)
        return np.mean(np.abs((y_test - y_pred) / y_test)) * 100
    
    # Evaluation of MAPE 

    result = MAPE(y_test, y_pred)
    print('Mean Absolute Percentage Error (MAPE):', round(result, 2), '%')
     # Evaluation of MAPE 

    result = MAPE(y_test, y_pred)
    print('Mean Absolute Percentage Error (MAPE):', round(result, 2), '%')
    
    # Calculate Adjusted R squared values 

    r_squared = round(metrics.r2_score(y_test, y_pred),6)
    adjusted_r_squared = round(1 - (1-r_squared)*(len(y)-1)/(len(y)-X.shape[1]-1),6)
    print('Adj R Square: ', adjusted_r_squared)
    
    #Save result
    
    results.append({
        "Model": models,
        'MAE': round(metrics.mean_absolute_error(y_test, y_pred),3),
        'MSE': round(metrics.mean_squared_error(y_test, y_pred),3),
        'RMSE': round(np.sqrt(metrics.mean_squared_error(y_test, y_pred)),3),
        'R2_score': round(metrics.r2_score(y_test, y_pred),6),
        'RMSLE': round(np.log(np.sqrt(metrics.mean_squared_error(y_test, y_pred))),3)
    })
    print('------------------------------------------------------------------------------------------------------------')

Model name:  LinearRegression()
Mean Absolute Error (MAE): 2233.741
Mean Squared Error (MSE): 9467104.671
Root Mean Squared Error (RMSE): 3076.866
R2_score: 0.552678
Root Mean Squared Log Error (RMSLE): 8.032
Mean Absolute Percentage Error (MAPE): 28.18 %
Mean Absolute Percentage Error (MAPE): 28.18 %
Adj R Square:  0.552385
------------------------------------------------------------------------------------------------------------
Model name:  DecisionTreeRegressor()
Mean Absolute Error (MAE): 1354.811
Mean Squared Error (MSE): 5155340.899
Root Mean Squared Error (RMSE): 2270.538
R2_score: 0.75641
Root Mean Squared Log Error (RMSLE): 7.728
Mean Absolute Percentage Error (MAPE): 68.67 %
Mean Absolute Percentage Error (MAPE): 68.67 %
Adj R Square:  0.75625
------------------------------------------------------------------------------------------------------------

/Users/hoangvulinh/miniforge3/lib/python3.10/site-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Model name:  RandomForestRegressor()
Mean Absolute Error (MAE): 1286.297
Mean Squared Error (MSE): 4245859.851
Root Mean Squared Error (RMSE): 2060.548
R2_score: 0.799383
Root Mean Squared Log Error (RMSLE): 7.631
Mean Absolute Percentage Error (MAPE): 68.01 %
Mean Absolute Percentage Error (MAPE): 68.01 %
Adj R Square:  0.799251
------------------------------------------------------------------------------------------------------------
Model name:  KNeighborsRegressor()
Mean Absolute Error (MAE): 1531.895
Mean Squared Error (MSE): 5324161.715
Root Mean Squared Error (RMSE): 2307.415
R2_score: 0.748433
Root Mean Squared Log Error (RMSLE): 7.744
Mean Absolute Percentage Error (MAPE): 17.29 %
Mean Absolute Percentage Error (MAPE): 17.29 %
Adj R Square:  0.748268
------------------------------------------------------------------------------------------------------------

/Users/hoangvulinh/miniforge3/lib/python3.10/site-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Model name:  ExtraTreesRegressor()
Mean Absolute Error (MAE): 1321.843
Mean Squared Error (MSE): 4617011.207
Root Mean Squared Error (RMSE): 2148.723
R2_score: 0.781846
Root Mean Squared Log Error (RMSLE): 7.673
Mean Absolute Percentage Error (MAPE): 68.13 %
Mean Absolute Percentage Error (MAPE): 68.13 %
Adj R Square:  0.781703
------------------------------------------------------------------------------------------------------------

/Users/hoangvulinh/miniforge3/lib/python3.10/site-packages/sklearn/ensemble/_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

Model name:  GradientBoostingRegressor()
Mean Absolute Error (MAE): 1793.213
Mean Squared Error (MSE): 5941028.495
Root Mean Squared Error (RMSE): 2437.423
R2_score: 0.719286
Root Mean Squared Log Error (RMSLE): 7.799
Mean Absolute Percentage Error (MAPE): 65.53 %
Mean Absolute Percentage Error (MAPE): 65.53 %
Adj R Square:  0.719102
------------------------------------------------------------------------------------------------------------
Model name:  XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)
Mean Absolute Error (MAE): 1290.625
Mean Squared Error (MSE): 3710607.5
Root Mean Squared Error (RMSE): 1926.294
R2_score: 0.824673
Root Mean Squared Log Error (RMSLE): 7.563
Mean Absolute Percentage Error (MAPE): 67.7 %
Mean Absolute Percentage Error (MAPE): 67.7 %
Adj R Square:  0.824558
------------------------------------------------------------------------------------------------------------
Model name:  BaggingRegressor()
Mean Absolute Error (MAE): 1309.712
Mean Squared Error (MSE): 4448981.757
Root Mean Squared Error (RMSE): 2109.261
R2_score: 0.789785
Root Mean Squared Log Error (RMSLE): 7.654
Mean Absolute Percentage Error (MAPE): 68.19 %
Mean Absolute Percentage Error (MAPE): 68.19 %
Adj R Square:  0.789647
------------------------------------------------------------------------------------------------------------
Model name:  Ridge()
Mean Absolute Error (MAE): 2237.818
Mean Squared Error (MSE): 9481630.098
Root Mean Squared Error (RMSE): 3079.226
R2_score: 0.551992
Root Mean Squared Log Error (RMSLE): 8.032

/Users/hoangvulinh/miniforge3/lib/python3.10/site-packages/sklearn/ensemble/_bagging.py:568: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return column_or_1d(y, warn=True)

Mean Absolute Percentage Error (MAPE): 65.01 %
Mean Absolute Percentage Error (MAPE): 65.01 %
Adj R Square:  0.551698
------------------------------------------------------------------------------------------------------------
Model name:  Lasso(alpha=0.1)
Mean Absolute Error (MAE): 2233.628
Mean Squared Error (MSE): 9466853.141
Root Mean Squared Error (RMSE): 3076.825
R2_score: 0.55269
Root Mean Squared Log Error (RMSLE): 8.032
Mean Absolute Percentage Error (MAPE): 65.03 %
Mean Absolute Percentage Error (MAPE): 65.03 %
Adj R Square:  0.552397
------------------------------------------------------------------------------------------------------------

/Users/hoangvulinh/miniforge3/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.897e+09, tolerance: 1.819e+07
  model = cd_fast.enet_coordinate_descent(

In [36]:
results

[{'Model': LinearRegression(),
  'MAE': 2233.741,
  'MSE': 9467104.671,
  'RMSE': 3076.866,
  'R2_score': 0.552678,
  'RMSLE': 8.032},
 {'Model': DecisionTreeRegressor(),
  'MAE': 1354.811,
  'MSE': 5155340.899,
  'RMSE': 2270.538,
  'R2_score': 0.75641,
  'RMSLE': 7.728},
 {'Model': RandomForestRegressor(),
  'MAE': 1286.297,
  'MSE': 4245859.851,
  'RMSE': 2060.548,
  'R2_score': 0.799383,
  'RMSLE': 7.631},
 {'Model': KNeighborsRegressor(),
  'MAE': 1531.895,
  'MSE': 5324161.715,
  'RMSE': 2307.415,
  'R2_score': 0.748433,
  'RMSLE': 7.744},
 {'Model': ExtraTreesRegressor(),
  'MAE': 1321.843,
  'MSE': 4617011.207,
  'RMSE': 2148.723,
  'R2_score': 0.781846,
  'RMSLE': 7.673},
 {'Model': GradientBoostingRegressor(),
  'MAE': 1793.213,
  'MSE': 5941028.495,
  'RMSE': 2437.423,
  'R2_score': 0.719286,
  'RMSLE': 7.799},
 {'Model': XGBRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, device=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, feature_types=None,
               feature_weights=None, gamma=None, grow_policy=None,
               importance_type=None, interaction_constraints=None,
               learning_rate=None, max_bin=None, max_cat_threshold=None,
               max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
               max_leaves=None, min_child_weight=None, missing=nan,
               monotone_constraints=None, multi_strategy=None, n_estimators=None,
               n_jobs=None, num_parallel_tree=None, ...),
  'MAE': 1290.625,
  'MSE': 3710607.5,
  'RMSE': 1926.294,
  'R2_score': 0.824673,
  'RMSLE': 7.563},
 {'Model': BaggingRegressor(),
  'MAE': 1309.712,
  'MSE': 4448981.757,
  'RMSE': 2109.261,
  'R2_score': 0.789785,
  'RMSLE': 7.654},
 {'Model': Ridge(),
  'MAE': 2237.818,
  'MSE': 9481630.098,
  'RMSE': 3079.226,
  'R2_score': 0.551992,
  'RMSLE': 8.032},
 {'Model': Lasso(alpha=0.1),
  'MAE': 2233.628,
  'MSE': 9466853.141,
  'RMSE': 3076.825,
  'R2_score': 0.55269,
  'RMSLE': 8.032}]

In [37]:
Result = pd.DataFrame(results)

In [38]:
Result

,Model,MAE,MSE,RMSE,R2_score,RMSLE
0,LinearRegression(),2233.741,9467104.671,3076.866,0.552678,8.032
1,DecisionTreeRegressor(),1354.811,5155340.899,2270.538,0.756410,7.728
2,"(DecisionTreeRegressor(max_features=1.0, rando...",1286.297,4245859.851,2060.548,0.799383,7.631
3,KNeighborsRegressor(),1531.895,5324161.715,2307.415,0.748433,7.744
4,"(ExtraTreeRegressor(random_state=7688158), Ext...",1321.843,4617011.207,2148.723,0.781846,7.673
5,([DecisionTreeRegressor(criterion='friedman_ms...,1793.213,5941028.495,2437.423,0.719286,7.799
6,"XGBRegressor(base_score=None, booster=None, ca...",1290.625,3710607.500,1926.294,0.824673,7.563
7,"(DecisionTreeRegressor(random_state=66820040),...",1309.712,4448981.757,2109.261,0.789785,7.654
8,Ridge(),2237.818,9481630.098,3079.226,0.551992,8.032
9,Lasso(alpha=0.1),2233.628,9466853.141,3076.825,0.552690,8.032

In [40]:
models=['LinearRegression','DecisionTreeRegressor','RandomForestRegressor','KNeighborsRegressor','ExtraTreesRegressor','GradientBoostingRegressor','XGBRegressor','BaggingRegressor','Ridge Regression','Lasso Regression']
result=pd.DataFrame({'Model_Name':models})
result['Adj_R_Square']=Result['R2_score']
result['Mean_Absolute_Error_MAE']=Result['MAE']
result['Root_Mean_Squared_Error_RMSE']=Result['RMSE']
result['Mean_Squared_Error_MSE']=Result['MSE']
result['Root_Mean_Squared_Log_Error_RMSLE']=Result['RMSLE']
result['R2_score']=Result['R2_score']
result=result.sort_values(by='Adj_R_Square',ascending=False).reset_index(drop=True)
result

,Model_Name,Adj_R_Square,Mean_Absolute_Error_MAE,Root_Mean_Squared_Error_RMSE,Mean_Squared_Error_MSE,Root_Mean_Squared_Log_Error_RMSLE,R2_score
0,XGBRegressor,0.824673,1290.625,1926.294,3710607.500,7.563,0.824673
1,RandomForestRegressor,0.799383,1286.297,2060.548,4245859.851,7.631,0.799383
2,BaggingRegressor,0.789785,1309.712,2109.261,4448981.757,7.654,0.789785
3,ExtraTreesRegressor,0.781846,1321.843,2148.723,4617011.207,7.673,0.781846
4,DecisionTreeRegressor,0.756410,1354.811,2270.538,5155340.899,7.728,0.756410
5,KNeighborsRegressor,0.748433,1531.895,2307.415,5324161.715,7.744,0.748433
6,GradientBoostingRegressor,0.719286,1793.213,2437.423,5941028.495,7.799,0.719286
7,Lasso Regression,0.552690,2233.628,3076.825,9466853.141,8.032,0.552690
8,LinearRegression,0.552678,2233.741,3076.866,9467104.671,8.032,0.552678
9,Ridge Regression,0.551992,2237.818,3079.226,9481630.098,8.032,0.551992

From the above results, the top 3 models by comparing errors, adj_R_square and R2_score values are

1. XGBRegressor
2. RandomForestRegressor
3. Bagging Regressor

Training the Data with these models

In [41]:
modelXGR.fit(x_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [42]:
#Predict the model with test data
y_pred = modelXGR.predict(x_test)

In [48]:
out=pd.DataFrame({'Price_actual':y_test.to_numpy().flatten(),'Price_pred':y_pred.flatten()})

In [49]:
out

      Price_actual    Price_pred
0            10844  12236.248047
1             4959   5894.597168
2            14781  12422.251953
3             3858   3595.580811
4            12898  14785.815430
...            ...           ...
2132          7408  12401.481445
2133          4622   4837.108398
2134          7452   6396.176270
2135          4823   4786.231445
2136         13731  12220.860352

[2137 rows x 2 columns]

In [50]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 1290.62451171875
RMSE: 1926.2937211131639
R²  : 0.8246733546257019

In [52]:
from sklearn.model_selection import RandomizedSearchCV
import xgboost as xgb
#RandomizedSearchCV
xgb_model = xgb.XGBRegressor(
    objective='reg:squarederror',
    random_state=42
)

param_grid = {
    'n_estimators': [200, 300, 500, 800, 1000],
    'learning_rate': [0.01, 0.03, 0.05, 0.1, 0.15],
    'max_depth': [3, 5, 7, 9, 12],
    'min_child_weight': [1, 3, 5, 7],
    'subsample': [0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.7, 0.8, 0.9, 1.0],
    'gamma': [0, 0.1, 0.3, 0.5],
}
random_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_grid,
    n_iter=30,
    cv=5,
    scoring='neg_root_mean_squared_error',
    n_jobs=-1,
    random_state=42,
    verbose=1
)
random_search.fit(x_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraint...
                                          num_parallel_tree=None, ...),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.7, 0.8, 0.9,
                                                             1.0],
                                        'gamma': [0, 0.1, 0.3, 0.5],
                                        'learning_rate': [0.01, 0.03, 0.05, 0.1,
                                                          0.15],
                                        'max_depth': [3, 5, 7, 9, 12],
                                        'min_child_weight': [1, 3, 5, 7],
                                        'n_estimators': [200, 300, 500, 800,
                                                         1000],
                                        'subsample': [0.7, 0.8, 0.9, 1.0]},
                   random_state=42, scoring='neg_root_mean_squared_error',
                   verbose=1)

In [53]:
print(random_search.best_params_)
print(random_search.best_score_)

{'subsample': 1.0, 'n_estimators': 500, 'min_child_weight': 3, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.3, 'colsample_bytree': 0.7}
-2069.75908203125

In [54]:
best_xgb = random_search.best_estimator_

In [56]:
random_search.best_estimator_

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.7, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0.3, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=3, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [55]:
y_pred = best_xgb.predict(x_test)

In [57]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 1355.35986328125
RMSE: 1962.6766162564836
R²  : 0.8179877996444702

In [58]:
#Default is better

In [59]:
print(random_search.best_params_)
print(random_search.best_score_)

{'subsample': 1.0, 'n_estimators': 500, 'min_child_weight': 3, 'max_depth': 5, 'learning_rate': 0.1, 'gamma': 0.3, 'colsample_bytree': 0.7}
-2069.75908203125

In [60]:
default_xgb = xgb.XGBRegressor(
    objective='reg:squarederror',
    random_state=42
)

default_xgb.fit(x_train, y_train)

y_pred_default = default_xgb.predict(x_test)

print("Default:")
print("MAE :", mean_absolute_error(y_test, y_pred_default))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred_default)))
print("R²  :", r2_score(y_test, y_pred_default))

Default:
MAE : 1290.62451171875
RMSE: 1926.2937211131639
R²  : 0.8246733546257019

In [ ]:
#Using default XGB to prediction